version: '3'
services:
  mysql:
    image: 'mysql:8.0.16'
    restart: always
    expose: 
      - 3306
    environment:
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    command: --init-file /data/db/init.sql
    volumes:
      - ./mysql:/data/db
  asterisk:
    build:
      dockerfile: Dockerfile
      context: ./asterisk



